import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "../blocks/Header/Header";
import Banner from "../blocks/Banner/Banner";
import AboutThis from "../blocks/AboutThis/AboutThis";
import Process from "../blocks/Process/Process";
import Footer from "../blocks/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bubble Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Banner />
        <AboutThis />
        <Process />
        <Footer />
      </main>
    </>
  );
}
